name: Test and build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable
      - run: |
          npm config set '@fortawesome:registry' '${{ secrets.FONTAWESOME_REGISTRY }}'
          npm config set '//npm.fontawesome.com/:_authToken' '${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}'
          pnpm install

      # TODO: code coverage, reporting, break these steps up
      - run: pnpm format
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm typecheck
      - run: pnpm build
